### ISSUE TITLE
enhancement - add actionswift support

### ISSUE THREAD

**Issue by johndpope** [TomasLinhart/SwiftGtk#13]
this library is a port of actionscript -> 
https://github.com/craiggrummitt/ActionSwift3/issues/2

(needs to be renamed to ActionScript4.)

**Comment by TomasLinhart** [comment]
I am sorry, can you clarify what do you mean? This library has no relation to ActionSwift or ActionScript.

**Comment by johndpope** [comment]
I will close this - so digging deeper into GTK - it appears there's all these controls etc.
Are you intending to build out this functionality?

![twf](https://user-images.githubusercontent.com/289994/31502574-7ff2d02a-af3b-11e7-9895-dc4da7d521f3.png)

The actionswift request is a far fetched dream to get linux to work with swift and a ui framework. 
As there's no UIKit for linux / that means there's no way to really build android apps with swift.
Adobe has signaled the end of swift / but there's still some die hard fans. 

Actionswift is a way to port code from actionscript to swift. 
That would piggy back on Adobe's tried and tested framework.

<img width="622" alt="screen shot 2017-10-12 at 10 55 39 am" src="https://user-images.githubusercontent.com/289994/31502748-f087854c-af3b-11e7-98ee-4f8b15315667.png">

Looking more closely at actionswift - it now seems tightly coupled with spritekit - so going to abandon the idea of this ever working.
