### ISSUE TITLE
Possible to use this with Xcode 7.3.1 / Swift 2.2?

### ISSUE THREAD

**Issue by cellularmitosis** [TomasLinhart/SwiftGtk#4]
Hi,

Can I use SwiftGTK using Xcode 7.3.1 and Swift 2.2?  Or do I have to set up Swift 3?

**Comment by TomasLinhart** [comment]
Hi, it should be possible with https://github.com/TomasLinhart/SwiftGtk/tree/0.1.0 but latest version requires Swift 3.
