### ISSUE TITLE
Compile error!

### ISSUE THREAD

**Issue by dev0zero** [TomasLinhart/SwiftGtk#7]
Hi,  i include your project in to my project and trying to build, after i got compile error 

<unknown>:0: error: build had 1 command failures
error: exit(1): /swift-3.0/usr/bin/swift-build-tool -f /home/user/swiftProjects/linSwift/.build/debug.yaml

**Comment by lliepmah** [comment]
It seems, I have same error, but I'll provide more verbose log:

```
/usr/include/glib-2.0/gio/gcredentials.h:72:1: error: declaration of 'pid_t' must be imported from module 'SwiftGlibc.POSIX.termios' before it is required
pid_t            g_credentials_get_unix_pid       (GCredentials    *credentials,
^
/usr/include/termios.h:30:17: note: previous declaration is here
typedef __pid_t pid_t;
                ^
/home/lliepmah/#Business/git/SwiftGtk/SwiftGtkDemo/Packages/SwiftGtk-0.1.0/Sources/Image.swift:5:8: error: could not build Objective-C module 'CGtk'
import CGtk
       ^
<unknown>:0: error: build had 1 command failures
error: exit(1): /home/lliepmah/swift-3.0.2/usr/bin/swift-build-tool -f /home/lliepmah/#Business/git/SwiftGtk/SwiftGtkDemo/.build/debug.yaml
```

**Comment by bmdelacruz** [comment]
I was able to fix this issue by modifying the dependency "CGtk-Linux". I'm still waiting for the [pull request](https://github.com/TomasLinhart/CGtk-Linux/pull/4) I made to be merged, You can try to run the sample application by modifying the package file, for the mean time, by changing the url of the dependency and the minor version from 1 to 2.

```swift
...
#elseif os(Linux)
    let gtkUrl = "https://github.com/bmdelacruz/CGtk-Linux"
...
  dependencies: [
    .Package(url: gtkUrl, majorVersion: 1, minor: 2)
...

**Comment by lliepmah** [comment]
@bmdelacruz, thank you kindly, it works perfectly!

**Comment by dev0zero** [comment]
i want to try!

**Comment by TomasLinhart** [comment]
I am sorry for a late answer. This issue is now resolved and it should work.
