### ISSUE TITLE
[Enquiry] What is supported?

### ISSUE THREAD

**Issue by lf-araujo** [TomasLinhart/SwiftGtk#8]
Thank you for your time and for this project.

You mention that only a subset of Gtk is supported. I couldn't find what is not supported... 

Could you explain or point me to documentation?

Best

**Comment by dev0zero** [comment]
it's looks like author is dead???? O.o no reply anymore...

**Comment by TomasLinhart** [comment]
I am not dead, fortunately. 😆  I focused on other things and somehow all messages got lost in thousands of notifications I got on GitHub. I am sorry.

There is no documentation at this point. You can go through [Sources](https://github.com/TomasLinhart/SwiftGtk/tree/master/Sources) and see what is implemented. It should not be hard. Feel free to open a pull request with documentation where you list implemented things.
